### ISSUE TITLE
<Params> multiple arguments

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#100]
The xml file looks like this:

``` xml
    <Params thing="A"  thing-zone="B"/>
```

Where it would work different to

``` xml
    <Params thing-zone="A"  thing="B"/>
```

 because order of attributes matters. BUT it's non conforming with XML standard\* .  I know that it's a bug in xml case file, but it's all over examples etc. and we do support that.
Therefore only supported version should be

``` xml
    <Params thing="B"/>
    <Params thing-zone="A" />
```

because order of child nodes is meaningful in XML.

We could add special name/zone argument/node:

``` xml
    <Params    thing="B"       other-thing="B"  />
    <Params   zone="zone"  thing="B"  other-thing="B" />
```

or

``` xml

       <Params   thing="B"   other-thing="B" >
       <Zonal   name="zone"     thing="B"      other-thing="B" />
       <Zonal   name="zone2"  thing="B"   other-thing="B" />
       </Params>
      <Params yetanother="1"/>
```

or maybe another.

In general this is bug IMHO, and need to be clarified before our miracle DOM-based handling ;)

@llaniewski , @shkodm  I could work on that, but in some cases it will break cases. We could make "converter" but still. And which option is most usefull/most expandable.

Other thing is that XML guys prefer

``` xml
<param>
<name>name</name>
<value>value</value>
</param>
```

or  (I would vote for this, still short but allows <[[CDATA and binary/base64 input easly)

``` xml
<param name="name">value</param>
```

over

``` xml
<param name="value" />
```

*) section 3.1 of the XML recommendation. It says, "Note that the order of attribute specifications in a start-tag or empty-element tag is not significant."',  http://stackoverflow.com/questions/726395/order-of-xml-attributes-after-dom-processing

**Comment by llaniewski** [comment]
Fixed by #241
