### ISSUE TITLE
PythonInline doesn't work on Travis-CI container

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#143]
Something is wrong when I try to run TCLB tests on Travis-CI container infrastructure with PythonInline

https://travis-ci.org/llaniewski/TCLB/jobs/232514466#L1268

Everything else seems to work.

Branch: https://github.com/llaniewski/TCLB/tree/travis-container

@mdzik any ideas?

**Comment by llaniewski** [comment]
Needed to solve #144

**Comment by mdzik** [comment]
I will look at it, and I hope soon. For now I have no idea :/

**Comment by mdzik** [comment]
I will investigate it (first I need docker host to access actual environment, ongoing :) ), but it seems related to something more than python version (I have the same). maybe python + gcc. I have used TLCB on new ubuntu without a problem so it seems somehow travis-specific

Regarding containers: as mentioned in #145 
I would vote to drop it: compile time (d2q9)
with sudo: ~7min
in container ~17min
not worth it

**Comment by mdzik** [comment]
All other referencing issues are closed, no need to investigate and fix (this is most likely Travis-specific problem)
