### ISSUE TITLE
[V6.2 RC] Automatic symmetries

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#158]
Add implicit Option "AutoSym" which will add symmetry node types and take care of symmetries in directly in LatticeAccess.

Needed:
Good definition on how to reflect each Field. Need different treatment of scalar fields, vector fields, and LBM densities.

**Comment by llaniewski** [comment]
solved by #160

**Comment by llaniewski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asdf](https://trello.com/c/eRGvIZ9i/1-asdf)

**Comment by mdzik** [comment]
??
