### ISSUE TITLE
TCLB License

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#187]
This issue is for contributors only.

If you agree for licensing your contribution to TCLB code under [GPL v3](https://choosealicense.com/licenses/gpl-3.0/) license, please add a comment in this Issue.

It is sufficient to write *I agree to license my contributions to TCLB under GPL v3.*

**Note**: Please don't start a discussion here. If you want to discuss the issue, please write an email.

**Comment by shkodm** [comment]
I agree to license my contributions to TCLB under GPL v3.

**Comment by ggruszczynski** [comment]
I agree to license my contributions to TCLB under GPL v3.

**Comment by mrutkowski-aero** [comment]
I agree to license my contributions to TCLB under GPL v3

**Comment by TravisMitchell** [comment]
I agree to license my contributions to TCLB under GPL v3

**Comment by mdzik** [comment]
I agree to license my contributions to TCLB under GPL v3


pt., 5 paź 2018 o 03:55 Travis Mitchell <notifications@github.com>
napisał(a):

**Comment by TGajek** [comment]
I agree to license my contributions to TCLB under GPL v3

**Comment by llaniewski** [comment]
Thank you all for the contribution.
