### ISSUE TITLE
Change of branch structure

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#192]
The current approach to development structure of branches on git proved to be very problematic. Additionally the master branch is rarely updated. That's why I decided that the repository will change the approach, to a one more resembling gitflow:
- master branch will be **the default branch to clone** and will have the last (mostly stable) version of TCLB, with fixes *(what develop is now)*
- develop will be the next release candidate version, with all big changes well defined in Issues and Pull Requests
- feature/... branch for big mods that do not work yet to be published (like chimera)

This approach will take effect in 2 weeks on 17.01.2019

*Please do not respond in this issue.*

*Notice for all people who have forked TCLB*: @hbcbh1999, @zcy9311, @vonHousen, @ndivaira, @edk261, @JunhuaPAN, @younglch, @dlightbody, @bhill23, @linhanGE, @Leixushu, @mrutkowski-aero, @uqdwan11, @yuelipku, @ggruszczynski, @Zitzeronion, @PeiyongWang, @JonMcCullough, @taraspiotr, @PabloOb, @myousefi2016, @Raflen, @okpatil4u, @niyaa, @franjesus, @wojtasMEiL, @hietwll, @TravisMitchell, @mdzik, @TGajek, @llaniewski, @shkodm

**Comment by ggruszczynski** [comment]
@llaniewski please, close branches which are already merged.

**Comment by llaniewski** [comment]
`master` branch now points to V6.2 and is the default branch.
Please remember to pull request to `develop` branch.
