### ISSUE TITLE
Is the TCLB can be used to simulate the fluid with free surface?

### ISSUE THREAD

**Issue by xuhenry** [CFD-GO/TCLB#212]
Hello everyone,
      Is the Code can be used to simulate the fluid with free surface? For example, I want to simulate the flowing  process of water in a channel, the water flow in from one side and flow out in other side.
Thanks a lot!
Best regard,
Henry

**Comment by llaniewski** [comment]
Not in macro scale. Only micro, droplet/bubble scale.

**Comment by xuhenry** [comment]
Can simulate the fluid with free surface, and the flow in and flow out boundary conditions?
Thanks a lot!

**Comment by llaniewski** [comment]
@xuhenry No. It is not a general purpose CFD code (at least not now). If you want a opensource solution, I would recommend trying doing it in OpenFOAM, or find a suitable code at https://www.cfd-online.com/Wiki/Codes .
