### ISSUE TITLE
Move copy and template to model makefile

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#216]
## Background
Because of the old policy of separating the code generation (done with `R`) and compilation, the two things are done in separate makefiles (`makefile.main` and `CLB/[model]/makefile`). The reason for that was to be able to generate the code on a machine with `R`, copy it to a cluster and then compile with `gcc`/`nvcc`.

## Problem
This makes a mess in `makefile.main`, and makes compilation wait for all the code generation to finish (which is slowing things down on parallel compilation).

## Possible solution
The code generation could be moved to the model makefile (`CLB/[model]/makefile`) to resolve this problem, as either way the code is always now compiled on architectures that have `R`.

**Comment by mdzik** [comment]
maybe a configure flag?
