### ISSUE TITLE
A separate ESYS-Particle xml element is needed

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#223]
## Problem
Because of my lazy naming, we ended up with a `<RemoteForceInterface>` element which **both** runs the Remote Force Interface (RFI) and executes (or connects to) ESYS-Particle code. This naming doesn't make sens and has to be changed.

## Proposed solution
Separate elements should be available. The `<RemoteForceInterface integrator="...">` should run RFI and connect to a selected integrator. A separate `<ESYSParticle>` element should run the ESYS-Particle code, and there should be different elements for other DEM codes (LAMMPS in near future).

## Comments
This change is not backwards compatible. **Old xml files involving RemoteForceInterface would have to be changed**.

**Comment by mdzik** [comment]
Might be we should use xml namespace?
```xml
<DEM:ESYSParticle ...>
<DEM:LAMMPS ...>
```
as a rule for "similar" nodes to make it clearer
it looks like pugi could handle that, (nodename will contain ":" imho)

**Comment by llaniewski** [comment]
Code modified by #225
Documentation in due time CFD-GO/TCLB_docs#11
