### ISSUE TITLE
Zenodoo

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#245]
https://zenodo.org/account/settings/github/

and we will get DOI for TCLB :D

**Comment by llaniewski** [comment]
@mdzik Looks kind of neat. I created a doi for 6.2:
[![DOI](https://zenodo.org/badge/40309607.svg)](https://zenodo.org/badge/latestdoi/40309607)

But we would much rather have our papers cited, wouldn't we? :-)

**Comment by llaniewski** [comment]
@mdzik @TravisMitchell OK. TCLB v6.3 has now a proper DOI: https://doi.org/10.5281/zenodo.3672102

We can use it to cite the software, but it would be good to keep citing the appropriate articles.
