### ISSUE TITLE
Issue with d2q9_pf_velocity model

### ISSUE THREAD

**Issue by TravisMitchell** [CFD-GO/TCLB#252]
Found an issue with d2q9_pf_velocity model. This seems to have been introduced in the CM update version of the code as the behaviour is correctly captured in the original d2q9_pf_velocity model. This was noticed when I was looking to replicate some current work in Yos et al. (2019) for a multiphase and or rtemplate tutorial for the documentation.

The below image shows the behaviour of the d2q9_pf_pressureEvolution and original d2q9_pf_velocity model in comparison to the current d2q9_pf_velocity model (MRT relaxation is used here, CM relaxation goes unstable relatively early):
![Comparison of behaviour](https://user-images.githubusercontent.com/17609184/71139587-4cda5700-225a-11ea-8521-311a7f5c1d9f.png)

The xml run files for the pressureEvolution, original d2q9, as well as current d2q9 (both mrt and cm) can be seen below:

[runFiles.zip](https://github.com/CFD-GO/TCLB/files/3981475/runFiles.zip)

Will look to fix this today, but just a notification for anyone using this model in its current form.

**Comment by TravisMitchell** [comment]
@llaniewski 

On my branches:
- v6.1_candidate-ZuHe_Modified_2D    model: d2q9_pf_velocityCheck
- d2q9_pf_velocity_Fix                           model: d2q9_pf_ZuHe_modified

These are the same models, but are finding different results between the code versions. I have pushed the run file that I am using in with the models

**Comment by llaniewski** [comment]
Update: the difference between versions proved to be the difference in interpretation of the cell position made here: 03032b1db60df352d7099882a570be60f98b2d02 (Dec 14, 2017)

**Comment by llaniewski** [comment]
@TravisMitchell what's the status on this?

**Comment by TravisMitchell** [comment]
@llaniewski the difference between versions was resolved as resulting from when we changed X,Y,Z values in Dynamics.c to reference +0.5 values. I believe this test case brought up a strong dependence on initial conditions with this model that I have not observed elsewhere.

**Comment by llaniewski** [comment]
@TravisMitchell yeah. I was thinking about the issue that you were getting different results/blowup if you centered you case on element, and not between elements. Does it still happen?

**Comment by TravisMitchell** [comment]
I will check now-ish, give me 30 mins
