### ISSUE TITLE
Compile issue on older gcc versions (pre 6.1)

### ISSUE THREAD

**Issue by TravisMitchell** [CFD-GO/TCLB#262]
For compiling with gcc prior to version 6.1, the default standard is C++98 where std::shared_ptr is not available. 

For anyone that hits this issue std::shared_ptr  was introduced in C++11, so you will need to add -std=c++11 (or higher) to your CPPFLAGS. Possibly worth putting check in configure to ensure later standard is being used?

**Comment by llaniewski** [comment]
This concerns #259 and `compare` tool. Needs to be fixed as c++11 is not yet universally supported on all our target platforms.

**Comment by llaniewski** [comment]
fixed by #261
