### ISSUE TITLE
Coveralls not working - no source to look at

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#31]
The file "CLB/d2q9/Geometry.cpp" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.

**Comment by llaniewski** [comment]
It's a problem of viewing only. Otherwise the coverage test works.
The coverage of Geometry.cpp decreased (https://coveralls.io/builds/5502064), because new geometry element was added, and no tests are using it.

**Comment by mdzik** [comment]
I know its a viewing problem. It's not important bug, but still it's a bug
;)

2016-03-22 14:48 GMT+01:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:
