### ISSUE TITLE
AddQuantity(name="XXX", unit="") generates undeterministic behaviour

### ISSUE THREAD

**Issue by ggruszczynski** [CFD-GO/TCLB#312]
I found that `unit=""` is sometimes (not) working - depending on luck in memory layout - some models works fine with this setting, others are likely to fail. 

```.sh

AddQuantity(name="PhaseField", unit="1.") # OK
AddQuantity(name="PhaseField", unit="") # depends on model
```

My configuration:
```bash
./configure --enable-double --enable-cpp11 --enable-graphics --with-cuda-arch=sm_60
```

I was running with GPU SERIAL CUDA Version: 11.0.

I was running with https://github.com/ggruszczynski/TCLB/tree/lemimg:
```bash
CLB/d2q9_diffusion/main some.weird.example.xml example/experimental/d2q9_diffusion.xml
```

The xml file looks like this https://github.com/ggruszczynski/TCLB/tree/lemimg/example/experimental:
```xml
<?xml version="1.0"?>
<CLBConfig version="2.0" output="output/diffusion/">
	<Geometry nx="512" ny="512">
		<SRT><Box/></SRT>
		<None name="special">
			<Box dx="40" dy="40" nx="150" ny="150"/>
		</None>
	</Geometry>
	<Model>
        <Param name="Init_PhaseField" value="0.1"/>
		<Param name="Init_PhaseField" zone="special" value="1.0" />
		<Param name="diffusivity_phi" value="0.1666"/>
    </Model>
    <Solve Iterations="10"><VTK Iterations="1"/></Solve>
	<!-- <Solve Iterations="100"><VTK Iterations="10"/></Solve> -->	<!-- Smoothing the population -->
	<!-- <Geometry><None mask="ADDITIONALS"><Box nx="512" ny="512"/></None></Geometry> -->
	<Solve Iterations="2000"><VTK Iterations="100"/></Solve>
</CLBConfig>
```

I get this error:
```
Paraview output for PhaseField is written as 1 everywhere.
```

Experimental model, which used to crash with `AddQuantity(name="PhaseField", unit="")` is here
https://github.com/ggruszczynski/TCLB/tree/lemimg/models/experimental/d2q9_diffusion

Expected behaviour:
`AddQuantity(name="XXX", unit="")` shall crash or say I am running with default `1`.

**Comment by llaniewski** [comment]
@ggruszczynski That is wierd. The unit converted should generate 1 from an empty string.

**Comment by llaniewski** [comment]
OK. I identified that the reason it returns `0` is that the `alt` method, which converts unit text into number is expecting a sum of unit expressions. A single unit expression, which would be empty, would be converted to 1 by default. But as the converted expects a sum (eg. `1m+2") it thinks an empty string means 0 elements in a sum, and returns 0.

That kind of makes sens, but makes it a bit inconsistent, as in places where text is interpreted with `alt`, the result will be `0`, and where it is interpreted as a single unit expression (line in `Units/gauge`), it will be `1`.

Returning `1` from `alt()` by default for a empty string, would make it consistent. The question is if we see edge cases in which this would break stuff?

**Comment by ggruszczynski** [comment]
Isn't it enought to forbid 
`AddQuantity(name="XXX", unit="")` 
and enforce to use either
`AddQuantity(name="XXX", unit="1")`
or 
`AddQuantity(name="XXX")` - with default 1?
