### ISSUE TITLE
R packages not found by configure, after install.sh rdep

### ISSUE THREAD

**Issue by ztdepztdep** [CFD-GO/TCLB#330]
I found that configure is not working

checking /usr/bin/R... exists
checking R package: optparse... yes
checking R package: numbers... yes
checking R package: rtemplate... configure: error: no

but I have installed the R packages by "tool/install rdep".
I want to know how to resolve this

**Comment by llaniewski** [comment]
Hi. What architecture you're working on? What did the `tools/install.sh rdep` print?

**Comment by ztdepztdep** [comment]
```
 sudo tools/install.sh rdep
Discovered Package Manager: apt-get
Installing optparse... OK
Installing numbers... OK
Installing yaml... OK
Downloading llaniewski.rtemplate... OK
Installing llaniewski.rtemplate... OK
Downloading llaniewski.gvector... OK
Installing llaniewski.gvector... OK
Downloading llaniewski.polyAlgebra... OK
Installing llaniewski.polyAlgebra... OK
```
Today i tried it again. but still give me the following error. It seems R cann't find the packages installed. 

```
checking /usr/bin/R... exists
checking R package: optparse... configure: error: no
```

**Comment by llaniewski** [comment]
Thanks, @ztdepztdep . I would ask you to copy paste here what these commands print:
```bash
which R
R --version
echo "R_LIBS_USER=$R_LIBS_USER"
R --slave -e '.libPaths()'
R --slave -e 'dir(.libPaths())'
R --slave -e 'library(optparse)'
R --slave -e 'library(rtemplate)'
```
Hopefully we can resolve this issue.

**Comment by ztdepztdep** [comment]
which R
/usr/bin/R

R --version
R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-suse-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

echo "R_LIBS_USER=$R_LIBS_USER"
R_LIBS_USER=

R --slave -e 'dir(.libPaths())'
 [1] "base"         "boot"         "class"        "cluster"      "codetools"   
 [6] "compiler"     "datasets"     "foreign"      "graphics"     "grDevices"   
[11] "grid"         "KernSmooth"   "lattice"      "MASS"         "Matrix"      
[16] "methods"      "mgcv"         "nlme"         "nnet"         "parallel"    
[21] "rpart"        "spatial"      "splines"      "stats"        "stats4"      
[26] "survival"     "tcltk"        "tools"        "translations" "utils"       

R --slave -e 'library(optparse)'
Error in library(optparse) : there is no package called ‘optparse’
Execution halted

R --slave -e 'library(rtemplate)'
Error in library(rtemplate) : there is no package called ‘rtemplate’
Execution halted

**Comment by llaniewski** [comment]
That is weird. Not even normal R Packages. But I don't know why the script is not reporting it. Could you try to manually install these packages:

Run `R` and execture:
```R
install.packages("optparse")
```

And see if there are no errors. After that you can exit R with "quit()". Then please download the other needed packages from github:
```bash
wget https://github.com/llaniewski/rtemplate/archive/master.tar.gz -O rtemplate.tar.gz
wget https://github.com/llaniewski/gvector/archive/master.tar.gz -O gvector.tar.gz
wget https://github.com/llaniewski/polyAlgebra/archive/master.tar.gz -O polyAlgebra.tar.gz
```
and then install them with:
```bash
R CMD INSTALL rtemplate.tar.gz 
R CMD INSTALL gvector.tar.gz 
R CMD INSTALL polyAlgebra.tar.gz 
```

That is basically what the `install.sh` script is doing, but maybe we'll see some additional errors.

**Comment by llaniewski** [comment]
@ztdepztdep I identified why the script was not showing the errors in the installation, and I'm fixing it in #332 . But I still don't know what is causing the packages fail to install on your computer. Please try to install them yourself (like above), and we'll see what are the errors.

**Comment by llaniewski** [comment]
@ztdepztdep comment posted by mistake in the wrong issue:

It works today! I don't know what had happened. I now charged the compute20 to compute60 in the make file. Hope it will not cause problems. 

```bash
ztdep@linux-9owh:~/Downloads/TCLB> make -j 20 d2q9
make: Circular CLB/d2q9/makefile <- CLB/d2q9/makefile dependency dropped.
  AUTO-DEP   CLB/d2q9/dep.mk
  RT         CLB/d2q9/makefile
make[1]: Entering directory '/home/ztdep/Downloads/TCLB/CLB/d2q9'
  G++        main.cpp
  NVCC       cuda.cu
  G++        vtkLattice.cpp
  G++        Solver.cpp
  NVCC       Lattice.cu
  NVCC       cross.cu
  LINKING    empty
  LINKING    compare
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'
make[1]: *** [makefile:63: cuda.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  LINKING    simplepart
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'
make[1]: *** [makefile:63: cross.o] Error 1
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'
```

**Comment by llaniewski** [comment]
@ztdepztdep Good to hear, I'm closing this issue.

As for the CUDA computational capability you can also change it with: 
```bash
./configure --with-cuda-arch=sm_60
```
