### ISSUE TITLE
`install.sh --rpackage` does not work properly

### ISSUE THREAD

**Issue by ggruszczynski** [CFD-GO/TCLB#331]
I found that `Installing --rpackage... OK` while it is not OK.
```
ggruszcz@rysy-n2 ~/rysy/TCLB $ tools/install.sh --rpackage buhahaha  # Honestly, I tried to install the 'png' package...
Discovered Package Manager: yum
Installing --rpackage... OK
```

My configuration:
```bash
ggruszcz@rysy-n2 ~/rysy/TCLB $ git fetch --all
Fetching origin
Fetching upstream
ggruszcz@rysy-n2 ~/rysy/TCLB $ git merge upstream/develop 
Already up-to-date.
ggruszcz@rysy-n2 ~/rysy/TCLB $ git branch -v
* develop                           f187227 [ahead 2] Merge pull request #329 from llaniewski/fix/grid3d
```

**Comment by llaniewski** [comment]
Possibly related: #330

**Comment by ztdepztdep** [comment]
It works today! I don't know what had happened. I now charged the compute20 to compute60 in the make file. Hope it will not cause problems. 


base) ztdep@linux-9owh:~/Downloads/TCLB> make -j 20 d2q9
make: Circular CLB/d2q9/makefile <- CLB/d2q9/makefile dependency dropped.
  AUTO-DEP   CLB/d2q9/dep.mk
  RT         CLB/d2q9/makefile
make[1]: Entering directory '/home/ztdep/Downloads/TCLB/CLB/d2q9'
  G++        main.cpp
  NVCC       cuda.cu
  G++        vtkLattice.cpp
  G++        Solver.cpp
  NVCC       Lattice.cu
  NVCC       cross.cu
  LINKING    empty
  LINKING    compare
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'
make[1]: *** [makefile:63: cuda.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  LINKING    simplepart
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'
make[1]: *** [makefile:63: cross.o] Error 1
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'
