### ISSUE TITLE
Remove obsolete wiki

### ISSUE THREAD

**Issue by ggruszczynski** [CFD-GO/TCLB#335]
I found that there is a nice documentation
https://docs.tclb.io/
and there is an obsolete one too:
https://github.com/CFD-GO/TCLB/wiki

I would suggest to **remove** the obsolete one to avoid confusion.

**Comment by llaniewski** [comment]
@mdzik is there anything you want to keep from the wiki before I delete it?

**Comment by llaniewski** [comment]
@ggruszczynski I would be glad if you contributed to the documentation at [TCLB_docs](https://github.com/CFD-GO/TCLB_docs)

**Comment by ggruszczynski** [comment]
@llaniewski a couple of LBM lectures is scheduled for the end of the semester.
The docs shall learn something as well ;)

**Comment by llaniewski** [comment]
@mdzik ,any comments?
