### ISSUE TITLE
Merge policy

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#34]
New rule proposal:
ANY new, model-related future/helper (auto BC, feq/collision helper etc.) will not be merged without reference to wiki (in code) OR at minimum meaningful API doc-string. Things like lib/boundary.R are unusable without that
 

Also, maybe we should come out with some merging guide, especially if we want someone to use it ;)

**Comment by llaniewski** [comment]
See: https://github.com/blog/2111-issue-and-pull-request-templates
Draft a proposal, then we can iterate.

**Comment by mdzik** [comment]
In pull request #44

**Comment by mdzik** [comment]
Should we close that one?
