### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by ztdepztdep** [CFD-GO/TCLB#348]
I found that ... is not working

Please fill:

   checking R package: optparse... configure: error: no

My configuration:
./configure --enable-graphics --with-cuda-arch=sm_30 --disable-graphics

**Comment by llaniewski** [comment]
Did you install "optparse" package in R?

You can install all neede packages with:
```
./tools/install.sh rdep
```

**Comment by ztdepztdep** [comment]
it works now. I have runned several examples. 
In the example "d2q9_SRT_example.xml", it gave a nearly "zero" velocity field. 
In the example "D2Q9_Poiseuille.xml", it gave a good veloicty field,  but the Rho field is at the order of 1E9. 
Could you please give me some suggestions.
Regards

**Comment by TravisMitchell** [comment]
Hi @ztdepztdep have you attempted any of the tutorials at https://tclb.io/ ? These are perhaps the best way to understand the TCLB code

**Comment by ztdepztdep** [comment]
> Hi @ztdepztdep have you attempted any of the tutorials at https://tclb.io/ ? These are perhaps the best way to understand the TCLB code

YES, i follow the tutorial in the doc. but not every example in the example give reasonable results. I cann't figure it out. I have tried to use cpu only, it also gives me the same results.

**Comment by llaniewski** [comment]
As @TravisMitchell said, it's good to start with the tutorials. The examples are setups which have to be sometimes changed for specific models. The settings names are different across models. To see all the settings for a model you can do:
```
make d2q9/summary
```
For instance, some authors call their acceleration "GraviationX", some "AccelerationX", and some model just have "ForceX".

You can think of TCLB, as a framework for high-performance LBM. The models are written by different people, and have specific goals. That is why they have different settings, bourdary conditions implemented, etc.

**Comment by TravisMitchell** [comment]
To add to the above ^^, as models are written by specific authors for their research purposes, you'll find the examples may only run for their respective model. If you receive warnings that Params are not defined when you run an example, it is a good indication that the example you are running is not designed for the model you have built, but you may be able to simply modify the params/boundary conditions if it has the domain geometry you want to run :)

**Comment by ztdepztdep** [comment]
<Param name="Velocity_x" value="0.01m/s"/>	</Model>

use Velocity_x will give correct results. "Velocity" cann't get it.
what is the difference

**Comment by TravisMitchell** [comment]
@ztdepztdep I do not understand what you are asking. 

As per the tutorials, check the Dynamics.R file for the model you are trying to run, it defines the parameters that can be set... If Velocity_x is used by the model developer (i.e is defined in the dynamics.r file), than this is what you need to use in your XML run file. Does this help with what you are trying to ask?

**Comment by ztdepztdep** [comment]
great! thanks.
Does TCLB suppor tmultiple GPUs automatically?

**Comment by llaniewski** [comment]
@ztdepztdep Yes. The idea is to use one MPI process per GPU. So if you have 2 GPUs on your PC, you just do:
```
mpirun -np 2 CLB/d2q9/main case.xml
```
