### ISSUE TITLE
Need for complete change to another CI provider

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#358]
Currently the Travis-CI integration stopped working. As Travis-CI pricing changed, I don't know if it is a good idea to continue testing there.

I think introduction of GitHub Actions stabbed Travis-CI in the back and it's slowly dying now.
We can:
- Fix the integration and migration to `travis-ci.com` (probably setup from 0) and stay with Travis-CI
- Migrate to GitHub Actions
- Migrate to CircleCI

**Comment by mdzik** [comment]
"Free for open source. We love the Open Source Community, and to show how
much we love it, upon validated request placed with our Support Team you
may receive free OSS credits for your public builds." I like Travis ;)

pt., 2 lip 2021 o 13:33 Łukasz Łaniewski-Wołłk ***@***.***>
napisał(a):

**Comment by llaniewski** [comment]
Fixed by #412
