### ISSUE TITLE
Change the installation of python for rtemplate

### ISSUE THREAD

**Issue by llaniewski** [CFD-GO/TCLB#380]
We need to change update [tools/install.sh](https://github.com/CFD-GO/TCLB/blob/develop/tools/install.sh#L276) for the changes introduced to rtemplate in https://github.com/llaniewski/rtemplate/pull/2 (move from rPython to reticulate).

**Comment by TravisMitchell** [comment]
no worries, I will do this tonight

**Comment by llaniewski** [comment]
fixed with #381
