### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kubagalecki** [CFD-GO/TCLB#451]
`attr` is never freed:

https://github.com/CFD-GO/TCLB/blob/5cdc2df782f1528e99822b24479199a27ec70ad6/src/LatticeContainer.inc.cpp.Rt#L64-L78

There's also no reason to allocate it dynamically, as far as I can tell.

**Comment by llaniewski** [comment]
Just patch it and PR to `develop` branch.

**Comment by kubagalecki** [comment]
Closed in #455
