### ISSUE TITLE
New repo

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#46]
...for tools/scripts that could be used to work witch CLB: preprocessing/post-processing/gui ;) etc
I was thinking about pyCLB, but it suggests python API. 
Nice acronym, or we go with TCLB-tools :]

**Comment by llaniewski** [comment]
I created: https://github.com/CFD-GO/TCLB_tools
I propose a separate directory for languages (R, py, bash, etc). And each python/R package in a subdirectory.

**Comment by mdzik** [comment]
Great minds think alike. I was really hoping for clb_hairy-robo-squirrel, but tools will do :)
