### ISSUE TITLE
This is preliminary issue:  "clean up" milestone

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#63]
**Things to be cleared BEFORE moving forward with TCLB:**
1. Put hold on _any_ changes in TCLB codebase
2. Separate models into _stable_/_experimental_/_obsolete_
3.  All current models are flagged _experimental_ (or obsolete)
4. Move d2q9 (_new?) and d3q19 (?) to _stable_ but:
   1. Unit test for values
   2. Improve comments and references. Remove/upgrade ALL obsolete BC code
   3. Rename to match conventions (nu->KinematicViscosity etc)
   4. Track nonneeded BC code/helper functions
   5. Rename things like CollisionMRT if name is misleading
5. Check which of models left in _experimental_ have actual support, assign maintainer and push him to clean model to match _stable_ standards
6. Clear out _experimental_ models from abandoned ones, move them to obsolete

Despite how it looks, I think it could be done in few hours. Big part of it is already done.

**Comment by llaniewski** [comment]
Started here:
https://github.com/CFD-GO/TCLB/tree/model-move

**Comment by mdzik** [comment]
Do we want to have /models instead of /src/models? (I can see no reason not to have /models)
How do we mark maintainer?
I propose:

-   **d2q9**, **d2q9_kuper** - @mdzik
-  **sw**, **d3q19** - @llaniewski 
-  **d3q27_cumulant** - @llaniewski 

I'm also voting to drop d3q19 in favour of d3q27 as a base model

I think that maintainer "go" should be required before any pull request to that model is merged

**Comment by mdzik** [comment]
For the reference: #76
If you would like to add tests or sth, push to develop, I will rebase it

**Comment by mdzik** [comment]
This is most likely dead idea :)
