### ISSUE TITLE
Obsolete сhunk of code 

### ISSUE THREAD

**Issue by shkodm** [CFD-GO/TCLB#66]
Surprisingly, I found out that ```src/inter.cpp``` is not actually used anywhere. Grepping it gives, that its only occurrence is the makefile. Last (and second..) commit to it dates back to 2014. Besides it includes Rcpp header, which is is not even TCLB dependency. 

@llaniewski , what was that? Should we just delete it?

**Comment by llaniewski** [comment]
Yeah. It's old. It's a interface for R. It allows to call TCLB from R (through Rcpp) - but probably it doesn't work anymore :D

**Comment by mdzik** [comment]
Drop it or comment it all out, leaving info that its deprecated. Separate pull/commit is recommended in such cases

**Comment by shkodm** [comment]
Closed via #68
