### ISSUE TITLE
Residuals/(convergence criterium)

### ISSUE THREAD

**Issue by shkodm** [CFD-GO/TCLB#78]
As far, as I remember we don't have any support for monitoring residuals. 
I am pretty sure, it is possible to implement both "Stop when certain value is reached" and also saving history of residuals, aka ANSYS-like functionality. All this applied to quantities("U", "T", whatever) 

Anyone  interested? I can try to implement it.

**Comment by llaniewski** [comment]
@shkodm What do you mean by residual?

We have a "Stop" element which stops when for instance something doesn't change (some global integral).

**Comment by mdzik** [comment]
So maybe wiki/test will be enough?

**Comment by shkodm** [comment]
Yea, I forgot about "Stop"... It should be enough.
