### ISSUE TITLE
FailCheck

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#79]
I found that FailCheck is not working

The xml file looks like this:
```xml
<Solve Iterations="100000">
<VTK Iterations="100" />
<Failcheck Iterations="50">
<VTK />
</Failcheck>
</Solve>
```

I get this error:

There IS complete NaN Rho field, but: on BC (left/right) it's not, so 
```C
                if (!cond) {
                        real_t tmp;
                        solver->lattice->GetRho(reg,&tmp);
                        cond = (std::isnan(tmp));
```
is *OK*, because temp is first element of Rho array, which is BC, and not NaN

@shkodm  I will fix that, but do we want 2 separate versions? Is this a bug or a future? :)

**Comment by shkodm** [comment]
It was intended behaviour of FailCheck, that it checks only top right corner of the mesh(es). Probably it's good idea to allow user to specify sampling point for it, as  </Failcheck dx="3" dz="4" dx="5" Iterations="50" />, and (0,0,0) to be the default.

**Comment by mdzik** [comment]
ping ;) https://github.com/shkodm/TCLB/pull/1

**Comment by mdzik** [comment]
Done in #80
